### ISSUE TITLE
Scripts for importing mongodb .json dump to arangodb?

### ISSUE THREAD

**Issue by TQPS** [yeti-platform/yeti-docker#3]
I've deployed this yeti version and it's up - everything appears connected.

Now I need to get my Mangodb dump into Arangodb. You mentioned on the previous Yeti repo that a script would be provided to assist in this migration process.

Could you please point me in that direction?

**Comment by tomchop** [comment]
We're working on a migration script here: https://github.com/yeti-platform/yeti/pull/956

**Comment by TQPS** [comment]
Ok. For context, I have a .json dump on the new docker setup host ready to import. 

The original Mongodb is on another host and we've put a change freeze on it.

Just in case it's assumed both dbs are on the same host.

**Comment by tomchop** [comment]
I see, thanks. The script in https://github.com/yeti-platform/yeti/pull/956 cares little about where your mongodb host is so long as you can connect to it. 

Actually, a JSON dump might be easier for us to import than connecting to a mongodb instance (given that the latest versions of mongo are making accessing references a bit painful). I'll experiment a bit more and keep you updated!

**Comment by TQPS** [comment]
Unfortunately, no one has been able to successfully migrate our old Mongo system to the new one.

Leadership want to scrap Yeti and go for a different platform.

We'll employ some grads to enter our entity, malware, investigation data etc manually to the new system.
