### ISSUE TITLE
Data no longer accessible since recent commit: 4769296

### ISSUE THREAD

**Issue by TQPS** [yeti-platform/yeti-docker#7]
We've had this version of yeti working just fine for since January, through updates and restarts and it's persisted.

Only difference is that the IP for the Arangodb alternates between .2 and .3

Since this latest commit, the server stops loading and although Arangodb loads and we can log in - there's no data. Hence, we log into Yeti and it shows no data either - obviously.

Server does not progress past these lines since update:
```
yeti-tasks     | [2024-02-28 06:23:25,270: INFO/MainProcess] mingle: searching for neighbors
yeti-tasks     | [2024-02-28 06:23:26,318: INFO/MainProcess] mingle: all alone
yeti-tasks     | [2024-02-28 06:23:26,377: INFO/MainProcess] celery@71ec5bc22754 ready.
yeti-api       | INFO:     Started server process [11]
yeti-api       | INFO:     Waiting for application startup.
yeti-api       | INFO:     Application startup complete.
yeti-tasks     | [2024-02-28 06:23:28,207: INFO/Beat] beat: Starting...
```

```
Working:
========
ubuntu@YETI2:~$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS        PORTS                                       NAMES
583bdb405b11   yetiplatform/yeti-frontend:latest   "/docker-entrypoint.…"   4 weeks ago   Up 19 hours   0.0.0.0:80->80/tcp, :::80->80/tcp           yeti-frontend
16beacca8209   yetiplatform/yeti:latest            "/docker-entrypoint.…"   4 weeks ago   Up 19 hours                                               yeti-tasks
c891d2aaea6d   yetiplatform/yeti:latest            "/docker-entrypoint.…"   4 weeks ago   Up 19 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   yeti-api
54b4d713269e   redis:latest                        "docker-entrypoint.s…"   4 weeks ago   Up 19 hours   6379/tcp                                    yeti-redis
24a1aadc37f6   arangodb                            "/entrypoint.sh aran…"   4 weeks ago   Up 19 hours   8529/tcp                                    yeti-arangodb
ubuntu@YETI2:~$ 

Post Update:
============
ubuntu@YETI2:~$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS         PORTS                                       NAMES
71ec5bc22754   yetiplatform/yeti:latest            "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes                                               yeti-tasks
04654f9fec4d   yetiplatform/yeti-frontend:latest   "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp           yeti-frontend
0cbc45c4646a   yetiplatform/yeti:latest            "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   yeti-api
2e4fa0e5df03   arangodb                            "/entrypoint.sh aran…"   5 minutes ago   Up 5 minutes   8529/tcp                                    yeti-arangodb
54b4d713269e   redis:latest                        "docker-entrypoint.s…"   4 weeks ago     Up 5 minutes   6379/tcp                                    yeti-redis
ubuntu@YETI2:~$ 
```

Logs from prior successful load show a happy Arangodb:
```
yeti-arangodb  | 2024-02-27T11:29:57Z [1] INFO [fe333] {engines} RocksDB recovery starting, scanning WAL starting from sequence number 80864296, latest sequence number: 80864504, active log files: 4, files in archive: 0
yeti-arangodb  | 2024-02-27T11:29:57Z [1] INFO [a4ec8] {engines} RocksDB recovery finished, WAL entries scanned: 212, recovery start sequence number: 80864296, latest WAL sequence number: 80864504, max tick value found in WAL: 0, last HLC value found in WAL: 1791954229242363905
yeti-api       | INFO:     Will watch for changes in these directories: ['/app']
yeti-api       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
yeti-api       | INFO:     Started reloader process [7] using StatReload
yeti-arangodb  | 2024-02-27T11:30:01Z [1] INFO [c1b63] {arangosearch} ArangoSearch maintenance: [1..1] commit thread(s), [1..1] consolidation thread(s)
yeti-arangodb  | 2024-02-27T11:30:01Z [1] INFO [71efd] {arangosearch} ArangoSearch execution parallel threads limit: 2
yeti-arangodb  | 2024-02-27T11:30:01Z [1] INFO [6ea38] {general} using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
yeti-arangodb  | 2024-02-27T11:30:01Z [1] INFO [cf3f4] {general} ArangoDB (version 3.11.6 [linux]) is ready for business. Have fun!
```

Logs post the commit:
```
yeti-arangodb  | 2024-02-28T06:23:03Z [8] INFO [c1b63] {arangosearch} ArangoSearch maintenance: [1..1] commit thread(s), [1..1] consolidation thread(s)
yeti-arangodb  | 2024-02-28T06:23:03Z [8] INFO [71efd] {arangosearch} ArangoSearch execution parallel threads limit: 2
yeti-arangodb  | 2024-02-28T06:23:03Z [8] INFO [7da27] {startup} server will now shut down due to upgrade, database initialization or admin restoration.
yeti-arangodb  | Initializing database...Hang on...
yeti-api       | INFO:     Will watch for changes in these directories: ['/app']
yeti-api       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
yeti-api       | INFO:     Started reloader process [7] using StatReload
yeti-tasks     | WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39abd45f90>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
yeti-arangodb  | Database initialized...Starting System...
yeti-arangodb  | 2024-02-28T06:23:17Z [1] INFO [e52b0] {general} ArangoDB 3.11.6 [linux] 64bit, using jemalloc, build refs/tags/v3.11.6 92c633dbf4d, VPack 0.2.1, RocksDB 7.2.0, ICU 64.2, V8 7.9.317, OpenSSL 3.0.12 24 Oct 2023
yeti-arangodb  | 2024-02-28T06:23:17Z [1] INFO [75ddc] {general} detected operating system: Linux version 6.5.0-21-generic (buildd@lcy02-amd64-091) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2
```

None of us are Docker experts but happy to be pointed in the right direction.

We are consumers of the data inside but can no longer access it.

**Comment by tomchop** [comment]
Thanks for the detailed issue! This is a tricky situation since docker doesn't persist data across container restarts (hence why we decided to add this line in the config). By adding the line in the `docker-compose.yaml` and doing `docker compose down && docker pull && docker compose up` you may have forced docker to create a new arangodb container for you, with no data.

* First off - did you do any backups of your data before updating?
* How exactly did you do the update? what commands did you run?
* What's the output of `docker ps -a`?


On another note the "connection refused" message from yeti-tasks may come if the yeti-tasks container has started before the arangodb container, in which case it will do a few retries but eventually succeed in connecting. You *should* see the CELERY logo etc after a few retries.

**Comment by TQPS** [comment]
- We do have a snapshot of a working version.

- The "upgrade" was just a git pull and it looks like this:

```
cd /opt/yeti
sudo git pull
cd prod
docker compose up
```

Performs as follows:
```
ubuntu@YETI2:~$ cd /opt/yeti
sudo git pull
cd prod
docker compose up
[sudo] password for ubuntu: 
warning: redirecting to https://github.com/yeti-platform/yeti-docker/
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 1.02 KiB | 260.00 KiB/s, done.
From http://github.com/yeti-platform/yeti-docker
   57284da..4769296  main       -> origin/main
Updating 57284da..4769296
Fast-forward
 prod/docker-compose.yaml | 2 ++
 1 file changed, 2 insertions(+)
[+] Running 5/5
 ✔ Container yeti-arangodb  Recreated                                                                                                                                       0.1s 
 ✔ Container yeti-redis     Created                                                                                                                                         0.0s 
 ✔ Container yeti-api       Recreated                                                                                                                                       0.2s 
 ✔ Container yeti-tasks     Recreated                                                                                                                                       0.2s 
 ✔ Container yeti-frontend  Recreated                                                                                                                                       0.1s 
Attaching to yeti-api, yeti-arangodb, yeti-frontend, yeti-redis, yeti-tasks
yeti-arangodb  | Initializing root user...Hang on...
```

docker-compose.yml is the only file being modified.

As stated earlier, this server has been bounced a few times and even received the last few updates without incident. The database has persisted although the IP we connect to it from changes between .2 and .3 - but we're ok with that.

- docker ps -a returns the following with the latest commit applied:
```
ubuntu@YETI2:~$ docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS       PORTS                                       NAMES
71ec5bc22754   yetiplatform/yeti:latest            "/docker-entrypoint.…"   3 hours ago   Up 3 hours                                               yeti-tasks
04654f9fec4d   yetiplatform/yeti-frontend:latest   "/docker-entrypoint.…"   3 hours ago   Up 3 hours   0.0.0.0:80->80/tcp, :::80->80/tcp           yeti-frontend
0cbc45c4646a   yetiplatform/yeti:latest            "/docker-entrypoint.…"   3 hours ago   Up 3 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   yeti-api
2e4fa0e5df03   arangodb                            "/entrypoint.sh aran…"   3 hours ago   Up 3 hours   8529/tcp                                    yeti-arangodb
54b4d713269e   redis:latest                        "docker-entrypoint.s…"   4 weeks ago   Up 3 hours   6379/tcp                                    yeti-redis
ubuntu@YETI2:~$ 
```

The full logs BEFORE the commit looks like this:
https://gist.github.com/TQPS/ad1be01da9a8b683cd205c52fefd39e6

and the logs continue after this and system starts normal,

The full logs AFTER the commit looks like this:
https://gist.github.com/TQPS/ad269fdb01438fe9edb8294fe8f48d93

and this is where the logs stop - the system does not continue.

Hope these help.

**Comment by tomchop** [comment]
These logs look good to me - Celery is attempting to connect to redis a few times, failing and then finally succeeding (that's when you see the logo). 

However, it seems that your db is gone given that the arangodb container was recreated (because there was a config change in the docker-compose file). Doing something like `docker cp 24a1aadc37f6:/var/lib/arangodb3/* /yeti-data` before running `docker compose up` would have probably been enough to avoid this.

At this stage, I'd recommend reimporting the database backup you have. You mentioned having a snapshot, what kind of snapshot are we talking about here?

**Comment by TQPS** [comment]
Update: using your guidance we restored our previous VM snapshot (before the update) and issued the following whilst it was running: 

`sudo docker cp 24a1aadc37f6:/var/lib/arangodb3 /yeti-data`

This has created and copied the contents to the destination local folder.

Then shut docker down and used the startup which includes the pull update:
```
cd /opt/yeti
sudo git pull
cd prod
docker compose up
```

Everything loads and data is now accessible through the web page again; both local and remote users. Additionally, the arangodb web interface is showing the correct values within the estimated document size - instead of 0.

<details>

![image](https://github.com/yeti-platform/yeti-docker/assets/66294837/e8b7d054-51ee-4154-8744-1c300b4a5d50)

</details>

We have performed a few `docker compose down`'s and confirmed the data remains consistent.

Unless you identify something we've done wrong, I suspect this is now working? We'll let you get back to developing the platform and introducing the ability to at least display our entities in alphabetical order :)

Appreciate the guidance. Thank you.

**Comment by tomchop** [comment]
Hey, thanks a lot for the update. The dunk about sorting is duly noted 😉 . That being said, the screenshot you're showing here is quite interesting - it seems like you're running the old UI (from December 2023). How long has it been since you've pulled the latest docker images? (i.e. `docker compose pull`). 

Doing `git pull` on the yeti-docker repo (like you did here) is not enough to get all updates (you're just updating the docker stuff, but not bringing in any changes from the API code or the UI). You still need to pull the latest releases that we publish on dockerhub (by doing some sort of `docker pull` or `docker compose pull` command)

And yes - once we figure that out with you we'll add the update commands to the documentation, because it seems it's not as clear as we thought it was 😄

**Comment by TQPS** [comment]
We welcome the heads up! We were not aware of any requirement to `docker compose pull`. Yes, we did not/can not see this in the current documentation. We've just done this now and can immediately see the difference. 

+1 for Dark mode.

We'll add this to our internal documentation and since the original issue has been resolved, we'll go ahead and close this issue as completed.

Appreciate your assistance. Thank you.

**Comment by tomchop** [comment]
Nice, I'm glad things are back to a normal state (I even think the sorting function is already implemented in the new UI!). If you are writing internal documentation on how to keep things up-to-date, and you feel this could also be useful for other people, I can only encourage you to contribute to https://github.com/yeti-platform/docs! It's all markdown and should be pretty straightforward to contribute :) Thanks!
